apiVersion: v1
kind: Secret
metadata:
  name: aws-ecr-authorization-secrets
data:
  aws-access-key-id: QUtJQUlUS0M2T05ZVkxPVFVGUFE=
  aws-secret-access-key: bGdjNDVmM2xKamRkSDBtOC96ck5LMnN1U1hzenRmemNhQSswTDRQbQ==
